import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Snippets",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // https://github.com/pacocoursey/next-themes#with-app
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className}
     bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100
      `}
      >
        <Providers>
          <Header />
          <main className="relative max-w-screen-lg mx-auto mt-14 py-4">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
